config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:show] do
    resources :items, only: [:create, :destroy]
  end
  
  root to: 'welcome#index'

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user

  default_scope { order('updated_at DESC') }

  validates :name, presence: true

  def days_left_text
    "#{self.days_left} days left to complete!"
  end

  def days_left
    7 - (DateTime.now.to_date - created_at.to_date).to_i
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end

  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    @user = current_user
    @item = @user.items.build(item_params)
    @new_item = Item.new

    if @item.save
      # flash[:notice] = "Item created"
    else
      # flash[:error] = "There was a problem saving your Item. Try again!"
    end

    respond_to do |format|
      format.html
      format.js
    end

  end

  def destroy
    @item = Item.find(params[:id])

    if @item.destroy
      # flash[:notice] = "Item destroyed"
    else
      # flash[:error] = "There was a problem destroying your Item. Try again!"
    end

    respond_to do |format|
      format.html
      format.js
    end

  end

  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @item = Item.new
    @items = @user.items
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<div class="row">
  <%= form_for [user, item], :html => {class: 'col s12 m8 offset-m2 l8 offset-l2'}, remote: true do |f| %>
  <h4 class="center-align">New item:</h4>
    <div class="input-field">
      <%= f.label :name, "Item name" %>
      <%= f.text_field :name %>
    </div>
    <br>
    <div class="actions center-align">
      <button class="btn waves-effect waves-light" type="submit" name="action">Save
        <i class="mdi-action-thumb-up right"></i>
      </button>
    </div>
  <% end %>
</div>

app/views/items/_item.html.erb
<li id="item-<%= item.id %>">
  <div class="row">
    <div class="col s12">
      <div class="row">
        <div class="col s9 m10 l10">
          <span><%= item.name %></span>
          <br>
          <% if item.days_left >= 5 %>
            <strong class="light-green-text"><%= item.days_left_text %></strong>
          <% elsif item.days_left >= 3 %>
            <strong class="amber-text"><%= item.days_left_text %></strong>
          <% else %>
            <strong class="red-text"><%= item.days_left_text %></strong>
          <% end %>
        </div>
        <div class="col s2 m1 l1">
          <a class="done btn-floating btn-small waves-effect waves-light green"><i class="mdi-action-done"></i></a>
        </div>
        <div class="del col s1 m1 l1">
          <%= link_to user_item_path(@user, item), class: 'done btn-floating btn-small waves-effect waves-light red', method: :delete, remote: true do %>
            <i class="mdi-action-delete"></i>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</li>

app/views/items/create.js.erb
<% if @item.valid? %>
   $('.js-items').prepend("<%= escape_javascript(render(@item)) %>");
   $('.new-item').html("<%= escape_javascript(render partial: 'items/form', locals: { user: @user, item: @new_item }) %>");
 <% else %>
   $('.new-item').html("<%= escape_javascript(render partial: 'items/form', locals: { user: @user, item: @item }) %>");
 <% end %>

app/views/items/destroy.js.erb
$('#item-' +<%= @item.id %>).fadeOut(function(){
  $(this).empty();
});

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bloccitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
  <%= stylesheet_link_tag    'application'%>
  <%= javascript_include_tag 'application'%>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="teal lighten-1">
    <div class="nav-wrapper">
      <% if current_user %>
        <%= link_to "BloccitOff", user_path(current_user), class: 'brand-logo' %>
      <% else %>
        <%= link_to "BloccitOff", root_path, class: 'brand-logo' %>
      <% end %>
        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="mdi-navigation-menu"></i></a>
        <ul class="right hide-on-med-and-down">
          <% if current_user %>
            <li><%= link_to "Items", user_path(current_user) %></li>
            <li><%= link_to "Settings", edit_user_registration_path %>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
        <ul id="mobile-demo" class="side-nav">
          <% if current_user %>
            <li><%= link_to "Items", user_path(current_user) %></li>
            <li><%= link_to "Settings", edit_user_registration_path %>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
          <% else %>
            <li><%= link_to "Login", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
          <% end %>
        </ul>
    </div>
  </nav>
  <% if flash[:notice] %>
    <div class="light-green accent-1 center-align" id="success">
      <span><%= flash[:notice] %><i class="close tiny mdi-content-clear right" id="close"></i></span>
    </div>
  <% elsif flash[:error] %>
    <div class="red lighten-3 center-align" id="error">
      <span><%= flash[:error] %><i class="close tiny mdi-content-clear right" id="close"></i></span>
    </div>
  <% elsif flash[:alert] %>
    <div class="yellow accent-4 center-align" id="alert">
      <span><%= flash[:alert] %><i class="close tiny mdi-content-clear right" id="close"></i></span>
    </div>
  <% end %>
  
  <% if !current_user %>
    <div class="row">
      <div class="intro purple darken-2 z-depth-1 col s12">
        <h1 class="white-text hide-on-small-only">BloccitOff</h1>
        <h2 class="white-text hide-on-med-and-up">BloccitOff</h2>
        <h5 class="white-text">A self destruct to-do list to keep you focused on the things that really matter!</h5>
        <%= link_to "Login", new_user_session_path, class: "waves-effect waves-light btn" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "waves-effect waves-light btn" %>
      </div>
    </div>
  <% end %>
  

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/users/show.html.erb
<div class="row">
  <div class="col s8 offset-s2 center-align hide-on-small-only">
    <h4>Welcome <%= @user.email %>!</h4>
  </div>
  <div class="col s12 center-align hide-on-med-and-up">
    <h5>Welcome <%= @user.email %>!</h5>
  </div>
</div>
<div class="row">
  <div class="col s12">
    <div class="row">
      <div class="col s12 m12 l8 offset-l2">
        <ul class="js-items">
          <%= render partial: 'items/item', collection: @items %>
        </ul>
      </div>
    </div>    
  </div>
</div>

<div class="row">
  <div class="new-item">
    <%= render partial: 'items/form', locals: { user: @user, item: @item } %>
  </div>
</div>